[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "device"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["rpi_ws281x", "spidev", "smbus2", "numpy", "gpiozero"]

[tool.setuptools]
packages = ["device"]
package-dir = { "device" = "." }
